### ISSUE TITLE
Simulation vo_server fail

### ISSUE THREAD

**Issue by AufarZakiev** [pal-robotics/pmb2_simulation#1]
Hello
I am working on launching the simulation of PMB2 in Gazebo.
ROS version is Indigo, Ubuntu 14.04, Gazebo 2.2
I was following [this tutorial](http://wiki.ros.org/Robots/PMB-2) and simulation works fine, all the sensor data is transferred and keyboard teleoperation works properly.
In order to make the movement autonomous, I have downloaded [pmb2_navigation](https://github.com/pal-robotics/pmb2_navigation) package.
Then, I launched `navigation.launch` from `pmb2_2dnav` package. It complained about `pal_navigation_sm`, so I downloaded this package from [here](https://github.com/pal-robotics/pal_navigation_sm.git). 
Relaunched, but `move_base` started to complain about `pal_vo_server` package.
There is no such package in PAL Robotics Github, so I don't know how to move further.
Could you help me please?
![image](https://user-images.githubusercontent.com/5558521/42574543-386e4c30-8527-11e8-9e89-9a9ba40496ff.png)

**Comment by v-lopez** [comment]
Hi @AufarZakiev, we've disabled that node.

We're in the process of reviewing all our public simulations, the most currently updated are TALOS, REEM-C and TIAGo (which uses the PMB2 for navigation), so you may want to try that as well. We have plans to migrate the PMB2 simulation to Kinetic during this year.

**Comment by AufarZakiev** [comment]
OK, now it complains on `pal_python` and so on
![image](https://user-images.githubusercontent.com/5558521/42625902-9e4cd4e0-85d1-11e8-8222-1d3547ec10ac.png)
I feel that PMB simulation is in process of migration and there is huge pain to resolve all these dependencies, isn't it?
We can move to Kinetic and TIAGo simulations, however, we have real PMB2 robot. Is the software developed and tested in Kinetic TIAGo simulation suitable for real PMB2 robot (by its kinematics, interfaces, etc)? It seems like not suitable, because as far as I know PMB2 itself has Indigo installed. 
Therefore, what should we do to synchronize our real and simulated robots software?

**Comment by v-lopez** [comment]
Hi, if you already have the real PMB2 robot, we have provided you with an ISO image in order to install a development computer with all the simulation and software required to use the PMB2.

You should be using that, since you will have access to all the features that we haven't published and that are guaranteed to work.

**Comment by AufarZakiev** [comment]
OK, we will try it ASAP.
We used it in the very beginning of the development, however, it has problems with USB, Wi-fi and video drivers and so on, so we tried to move to common Ubuntu to avoid them.
I had to mention about real robot in initial issue post, yeah? :)
Sorry for this, we will use Developer OS further.
Thank you very much for response and patience!

**Comment by jordi-pages** [comment]
@AufarZakiev 

Dear Aufar, could you contact us by sending an email to tiago-support@pal-robotics.com in order to have your official support account created?

Thanks in advance

**Comment by AufarZakiev** [comment]
@jordi-pages 
Sorry for long response, I will do it in seconds.
