### ISSUE TITLE
Can't launch PMB2 ROS 2 Simulation in ROS Humble

### ISSUE THREAD

**Issue by roberottt** [pal-robotics/pmb2_simulation#4]
Hello, 

I'm trying to use the PMB2 ROS simulation in ROS Humble. I have set up the workspace and installed all the dependencies , but when I try to launch the simulation in Gazebo with  `ros2 launch pmb2_gazebo pmb2_gazebo.launch.py` I get this error:

![pal2](https://user-images.githubusercontent.com/71451848/222423387-258376da-1704-4e58-8030-e9f9398c2205.png)

I don't understand why this error is shown because the robot is spawned correctly in Gazebo. The joint_state_broadcaster and mobile_base_controller are succesfully loaded too.

Do I need anything else? 

This is the full output:
[output.txt](https://github.com/pal-robotics/pmb2_simulation/files/10870952/output.txt)

**Comment by saikishor** [comment]
Hello @roberottt,

Thank you for showing interest in our PMB2 simulation. Are you using Cyclone DDS for the simulation as mentioned in the [prerequisites](https://github.com/pal-robotics/pmb2_simulation/tree/humble-devel#prerequisites).

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by Noel215** [comment]
Hi @roberottt!!

That's an issue of `ros2_control` that has been already patched. You can see it in https://github.com/ros-controls/ros2_control/pull/957, but probably it won't be available until the next humble sync.

**Comment by roberottt** [comment]
Hi @Noel215 @saikishor !

Thanks for the answer! We will wait to the next humble sync then. Is there something that we could do to solve this problem in the meantime?

**Comment by saikishor** [comment]
Hello @roberottt,

You can clone and build the ros2_control[ros2_control](https://github.com/ros-controls/ros2_control/tree/humble)  humble branch in your local workspace and compile it. This should solve your issue for now.

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by roberottt** [comment]
Hello @saikishor @Noel215, 
I have just compiled the humble branch in my local workspace but I'm getting this error now:

![Screenshot from 2023-03-03 11-25-05](https://user-images.githubusercontent.com/71451848/222696250-c30b441c-ff6d-4bc6-b99f-edbd85a0b41a.png)

**Comment by Noel215** [comment]
@roberottt, to make it work you have to clone also [gazebo_ros2_control](https://github.com/ros-controls/gazebo_ros2_control/tree/humble) humble branch because it needs to be compiled against the `ros2_control` version you are using

**Comment by roberottt** [comment]
@Noel215, cloning and compiling the gazebo_ros2_control humble branch solved the problem. Thank you very much!
