### ISSUE TITLE
nav2 simulation example doesn't work

### ISSUE THREAD

**Issue by david-wb** [pal-robotics/pmb2_simulation#5]
When I try to launch the gazebo + nav2 simulation, it throws an exception: `package 'pal_nav2_bringup' not found`

Full output:
```
:~/pmb2_public_ws$ ros2 launch pmb2_gazebo pmb2_gazebo.launch.py is_public_sim:=true navigation:=true
[INFO] [launch]: All log files can be found below /home/chroma/.ros/log/2024-05-06-11-41-37-930086-chroma-HP-ProBook-650-G2-8794
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): "package 'pal_nav2_bringup' not found, searching: ['/home/chroma/pmb2_public_ws/install/urdf_test', '/home/chroma/pmb2_public_ws/install/pmb2_simulation', '/home/chroma/pmb2_public_ws/install/pmb2_robot', '/home/chroma/pmb2_public_ws/install/pmb2_navigation', '/home/chroma/pmb2_public_ws/install/pmb2_gazebo', '/home/chroma/pmb2_public_ws/install/pmb2_2dnav', '/home/chroma/pmb2_public_ws/install/pmb2_laser_sensors', '/home/chroma/pmb2_public_ws/install/pmb2_bringup', '/home/chroma/pmb2_public_ws/install/pmb2_description', '/home/chroma/pmb2_public_ws/install/pmb2_controller_configuration', '/home/chroma/pmb2_public_ws/install/pal_navigation_cfg', '/home/chroma/pmb2_public_ws/install/pal_navigation_cfg_bringup', '/home/chroma/pmb2_public_ws/install/pal_navigation_cfg_params', '/home/chroma/pmb2_public_ws/install/pal_maps', '/home/chroma/pmb2_public_ws/install/pal_gazebo_worlds', '/home/chroma/pmb2_public_ws/install/launch_pal', '/opt/ros/humble']"
```
How can I install the missing package? Thanks for your help.

**Comment by MrVBian** [comment]
I encountered the same situation, how did you solve it. Thank you for your guidance

**Comment by david-wb** [comment]
@MrVBian Yes, I had to manually download `pmb2_navigation` package to the src folder of the workspace and rebuild, but then I ran into other problems. It seems this repo is severely outdated.

**Comment by MrVBian** [comment]
@david-wb  Thank you for your reply. I solved this problem and shared it with you.
I updated the tiago_navigation repositories like you. But I seem to have a step more than you, and execute the `vcs pull` instructions in the roots of the project. Hope to help you.
If my answer can't help you. At least for me, the project can be running, I suggest you open the problem.I made a docker container, if you need to contact me.
